apiVersion: v1
kind: svc
metadata:
  name: {{ include "guestbook.fullname" . }}
  labels:
    {{- include "guestbook.labels" . | nindent 4 }}
spec:
  type: {{ .Values.svc.type }}
  ports:
    - port: {{ .Values.svc.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "guestbook.selectorLabels" . | nindent 4 }}

